export const GET_USER = "GET_USER";
export const USER_LOGOUT = "USER_LOGOUT";
// export const GET_USER_ACCOUNT = "GET_ACCOUNT";
export const UPDATE_BALANCE = "UPDATE_BALANCE";
export const ACTUATE_TRANSACTION = "ACTUATE_TRANSACTION";
// export const GET_TRANSACTION_HISTORY = "GET_TRANSACTION_HISTORY"